### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by Askmewho** [ronbrogan/OpenH2#12]
Hi!! Nice project! This is targeting linux/opengl/vulkan too? also.. How far you are by now??

**Comment by ronbrogan** [comment]
I'm utilizing .net core, and have run an older version on linux with success. However, I develop on windows and plan to address xplat once the project is in a state where other people would feasibly want to run it. Currently using OpenGL for rendering, but it's very possible I'll end up moving to/also supporting vulkan. 

As far as the current state of things: it's by no means "playable" or a "game". Animations and sounds aren't even implemented yet. 
It's essentially a bare bones halo 2 map loader + rendering engine at the moment. 

This project is mostly a research and development platform for me at the moment. The goal is to eventually get to a state where someone could download and play the game using the engine, but there's no timeline for that.

**Comment by Askmewho** [comment]
Thanks for the infoo!
